name = "ezakat-ocr-scanner-v2"
main = ".open-next/worker.js"
compatibility_date = "2026-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "38fc8e5584b94006a34b07549d2287b9"
